[package]
name = "generic-openapi-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
openapiv3 = "2.0.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
tokio = { version = "1.0", features = ["full"] }
