openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: A simple API for testing CLI client generation
servers:
  - url: http://localhost:9999
    description: JSON Server

paths:
  /users:
    get:
      operationId: getUsers
      summary: Get all users
      parameters:
        - name: _page
          in: query
          required: false
          schema:
            type: integer
        - name: _limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      operationId: createUser
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{id}:
    get:
      operationId: getUser
      summary: Get a single user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /posts:
    get:
      operationId: getPosts
      summary: Get all posts
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      operationId: createPost
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '201':
          description: Created post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
      required:
        - id
        - name
        - email
        - role

    UserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        role:
          type: string
      required:
        - name
        - email
        - role

    Post:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        title:
          type: string
        body:
          type: string
      required:
        - id
        - userId
        - title
        - body

    PostInput:
      type: object
      properties:
        userId:
          type: integer
        title:
          type: string
        body:
          type: string
      required:
        - userId
        - title
        - body
